### ISSUE TITLE
words already colored during first use

### ISSUE THREAD

**Issue by levdopa** [hsnborn22/LinGo#9]
I just built from source and used it for the first time and some words are already colored green/red/yellow even though I would like everything to be grey. idk if this is on purpose or not. I ran sed -i 's/1/0/g' words.json (repeat with 2,3) to make everything grey. Also I had this error while building 'Package alsa was not found in the pkg-config search path. Perhaps you should add the directory containing `alsa.pc'' which is fixed by installing libasound2-dev or alsa-lib-devel on most distros so maybe add a dependency list on the install page

**Comment by hsnborn22** [comment]
Ok so I will address the two issues separately:

Issue #1 is completely normal; this is because in order to allow for immediate testing of new features I kept some example texts in the source code. Fixing this is very simple; all you have to do is go into the folder of the language you're studying and removing the file "words.json" as well as the file "dictionary.txt" (if it is there)

Issue #2: For issue #2 all you have to do is install alsa with this command:

`sudo apt install libasound2-dev`
